sudo: required

language: c

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t amtlib/wine-fedora .

script:
  - docker run --rm amtlib/wine-fedora wine --version
  
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
