sudo: required

language: c

services:
  - docker

before_install:
  - sudo cat /etc/docker/daemon.json
  - echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
  - service docker restart
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --squash -t amtlib/wine-fedora .

script:
  - docker run --rm amtlib/wine-fedora wine --version
  
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
