sudo: required

language: c

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - for branch in latest stable 2.18 3.1 3.2 3.3 3.4 3.5; do docker build -t amtlib/wine-fedora:$branch $branch; done

script:
  - docker run --rm amtlib/wine-fedora wine --version
  
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
