#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
for branch in latest stable 2.18 3.1 3.2 3.3 3.4 3.5; do docker push $DOCKER_USERNAME/wine-fedora:$branch; done
